baseURL = 'https://ghaniafza.github.io/'
languageCode = 'en-us'
title = 'Ghania Fza'
theme = 'nostyleplease'

custom_css = ["css/custom.css"]

[params]
  [params.theme_config]
    appearance = "light"
    back_home_text = ". . /"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
